---
DS 600 - Assignment_R
Ankur Patel
3/12/18
---

# Created text file of header followed by data (consisting of five attributes) about six students

```{r}
getwd()
setwd("C:/Users/Ankur/Documents/Data Science/Courses/DS 600")
```

```{r}
data <- read.table("problem1.txt", header=TRUE, row.names="id", sep=",")
print(data)
```

```{r}
str(data)
```


# Create MySQL database

```{r}
install.packages("RMySQL")
library(RMySQL)
mydb <- dbConnect(MySQL(), user="root", password="ankur715", host="localhost")
dbSendQuery(mydb, "CREATE DATABASE supplierpart;")
dbSendQuery(mydb, "USE supplierpart;")
dbSendQuery(mydb, "CREATE TABLE suppliers(sid INT, sname TEXT, address TEXT);")
dbSendQuery(mydb, "CREATE TABLE parts(pid INT, pname TEXT, color TEXT);")
dbSendQuery(mydb, "CREATE TABLE catalog(sid INT, pid INT, cost numeric(8,2));")
dbSendQuery(mydb, "INSERT INTO suppliers VALUES(1,'Acme Widget Suppliers','1 Grub St., Potemkin Village, IL 61801');")
dbSendQuery(mydb, "INSERT INTO suppliers VALUES(2,'Big Red Tool and Die','4 My Way, Bermuda Shorts, OR 90305');")
dbSendQuery(mydb, "INSERT INTO parts VALUES(1,'Left Handed Bacon Stretcher Cover','Red');")
dbSendQuery(mydb, "INSERT INTO parts VALUES(2,'Smoke Shifter End','Black');")
dbSendQuery(mydb, "INSERT INTO parts VALUES(3,'Acme Widget Washer','Red');")
dbSendQuery(mydb, "INSERT INTO catalog VALUES(1,1,0.50);")
dbSendQuery(mydb, "INSERT INTO catalog VALUES(1,2,0.50);")
dbSendQuery(mydb, "INSERT INTO catalog VALUES(1,3,11.70);")
dbSendQuery(mydb, "INSERT INTO catalog VALUES(2,2,0.55);")
dbSendQuery(mydb, "INSERT INTO catalog VALUES(2,3,7.95);")
resultS <- fetch(dbSendQuery(mydb, "SELECT * from suppliers;"))
resultP <- fetch(dbSendQuery(mydb, "SELECT * from parts;"))
resultC <- fetch(dbSendQuery(mydb, "SELECT * from catalog;"))
```
```{r}
print(resultS)
```
```{r}
print(resultP) 
```
```{r}
print(resultC)
```


# MASS package Car93 object 

```{r}
library(MASS)
Cars93
str(Cars93)
```
```{r}
summary(Cars93$Type)
```
```{r}
summary(Cars93$Origin)
```
```{r}
table(Cars93$Type, Cars93$Origin)
```